id: I6130A8C2
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T13:21:05.773637'
last_modified: '2022-06-19T13:21:05.773656'
parser: null
source_metadata:
  title: Hagiography of Ri khrod pa Blo gros brtan pa (1315/16-1358); Lamdre Lobshe,
    vol. ka, title no. 17, from the chronological biographies of the Lamdre lineage
    masters
  author: དཔལ་ལྡན་ཚུལ་ཁྲིམས།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-08-19);
    converted from external file, unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  - 'XML download privilege required: No'
  - 'Downloaded: 0 times'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/368
  bases:
    be53:
      title: Hagiography of Ri khrod pa Blo gros brtan pa (1315/16-1358); Lamdre Lobshe,
        vol. ka, title no. 17, from the chronological biographies of the Lamdre lineage
        masters
      order: 1
      base_file: be53.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
